Bistooltip_classes = {}
Bistooltip_phases = {}

Bistooltip_classes_indexes = {
    ["Death knight"] = 1,
    ["Druid"] = 2,
    ["Hunter"] = 3,
    ["Mage"] = 4,
    ["Paladin"] = 5,
    ["Priest"] = 6,
    ["Rogue"] = 7,
    ["Shaman"] = 8,
    ["Warlock"] = 9,
    ["Warrior"] = 10
}

Bistooltip_spec_icons = {};
Bistooltip_spec_icons["Death knight"] = {};
Bistooltip_spec_icons["Death knight"]["classIcon"] = 135771;
Bistooltip_spec_icons["Death knight"]["Blood tank"] = 135770;
Bistooltip_spec_icons["Death knight"]["Frost"] = 135773;
Bistooltip_spec_icons["Death knight"]["Unholy"] = 135775;
Bistooltip_spec_icons["Druid"] = {};
Bistooltip_spec_icons["Druid"]["classIcon"] = 625999;
Bistooltip_spec_icons["Druid"]["Balance"] = 136096;
Bistooltip_spec_icons["Druid"]["Feral tank"] = 132276;
Bistooltip_spec_icons["Druid"]["Feral dps"] = 132115;
Bistooltip_spec_icons["Druid"]["Restoration"] = 136041;
Bistooltip_spec_icons["Hunter"] = {};
Bistooltip_spec_icons["Hunter"]["classIcon"] = 626000;
Bistooltip_spec_icons["Hunter"]["Beast mastery"] = 132164;
Bistooltip_spec_icons["Hunter"]["Marksmanship"] = 132222;
Bistooltip_spec_icons["Hunter"]["Survival"] = 132215;
Bistooltip_spec_icons["Mage"] = {};
Bistooltip_spec_icons["Mage"]["classIcon"] = 626001;
Bistooltip_spec_icons["Mage"]["Arcane"] = 135932;
Bistooltip_spec_icons["Mage"]["Fire"] = 135810;
Bistooltip_spec_icons["Mage"]["Fire FFB"] = 236217;
Bistooltip_spec_icons["Mage"]["Frost"] = 135846;
Bistooltip_spec_icons["Paladin"] = {};
Bistooltip_spec_icons["Paladin"]["classIcon"] = 626003;
Bistooltip_spec_icons["Paladin"]["Holy"] = 135920;
Bistooltip_spec_icons["Paladin"]["Protection"] = 135893;
Bistooltip_spec_icons["Paladin"]["Retribution"] = 135873;
Bistooltip_spec_icons["Priest"] = {};
Bistooltip_spec_icons["Priest"]["classIcon"] = 626004;
Bistooltip_spec_icons["Priest"]["Discipline"] = 135987;
Bistooltip_spec_icons["Priest"]["Holy"] = 135953;
Bistooltip_spec_icons["Priest"]["Shadow"] = 136207;
Bistooltip_spec_icons["Rogue"] = {};
Bistooltip_spec_icons["Rogue"]["classIcon"] = 626005;
Bistooltip_spec_icons["Rogue"]["Assassination"] = 132292;
Bistooltip_spec_icons["Rogue"]["Combat"] = 132090;
Bistooltip_spec_icons["Rogue"]["Subtlety"] = 132320;
Bistooltip_spec_icons["Shaman"] = {};
Bistooltip_spec_icons["Shaman"]["classIcon"] = 626006;
Bistooltip_spec_icons["Shaman"]["Elemental"] = 136048;
Bistooltip_spec_icons["Shaman"]["Enhancement"] = 136051;
Bistooltip_spec_icons["Shaman"]["Restoration"] = 136052;
Bistooltip_spec_icons["Warlock"] = {};
Bistooltip_spec_icons["Warlock"]["classIcon"] = 626007;
Bistooltip_spec_icons["Warlock"]["Affliction"] = 136145;
Bistooltip_spec_icons["Warlock"]["Demonology"] = 136172;
Bistooltip_spec_icons["Warlock"]["Destruction"] = 136186;
Bistooltip_spec_icons["Warlock"]["Destruction fire"] = 136186;
Bistooltip_spec_icons["Warrior"] = {};
Bistooltip_spec_icons["Warrior"]["classIcon"] = 626008;
Bistooltip_spec_icons["Warrior"]["Arms"] = 132292;
Bistooltip_spec_icons["Warrior"]["Fury"] = 132347;
Bistooltip_spec_icons["Warrior"]["Protection"] = 134952;